export const ADD_TODO = 'ADD_TODO';
export const REMOVE_TODO = 'REMOVE_TODO';
export const EDIT_TODO = 'EDIT_TODO';
export const MODIFY_TODO_COMPLETED = 'MODIFY_TODO_COMPLETED';
export const TOGGLE_ALL_COMPLETED = 'TOGGLE_ALL_COMPLETED';
export const GO_FILTER_TODOS = 'GO_FILTER_TODOS';
export const CLEAR_COMPLETED_TODOS = 'CLEAR_COMPLETED_TODOS';